### ISSUE TITLE
Naming of package

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/hepstats#13]
Hey, we've discussed at CHEP about a few things, including naming of packages. Maybe the name `scikit-stats` implies a too broad scope, since it is not a general scikit statistics package, but rather something like `hep-stats`?

Or what is your take on the name?

(don't remember all the people I discussed that with, so can't tag anyone, maybe @eduardo-rodrigues ?)

**Comment by marinang** [comment]
@mayou36 I was slightly uncomfortable with the name at the beginning but after few discussions with the admins it was decided it was the best choice (see https://github.com/scikit-hep/scikit-hep/issues/88).

It’s true this package is hep specific. Names like skhep-statistics was proposed, I didn’t think of the short version skhep-stats which is similar to hep-stats. I think your point is fair but at the same time scikit-stats didn’t exist before due to already existing packages such as scipy.stats, but this can be misleading for non hep people. Let’s see what @eduardo-rodrigues and @HDembinski  think.

**Comment by HDembinski** [comment]
I would prefer `hep-stats` over `scikit-stats` in agreement with the argument  above.

**Comment by marinang** [comment]
And would you prefer `hep-stats` over `hepstats` ?  Then how one should import the package

```python
import hep-stats as hstats 
```

?

**Comment by eduardo-rodrigues** [comment]
Hi all, yeah, names are a tricky business. @mayou36 has a point about scope.

I have no strong preference but `hepstats` seems just fine to me. It is probably a bit better than `hep-stats`, and one can still do `import hepstats as hs` if you do not want to simply use `hepstats`, which I find fine, actually.

**Comment by marinang** [comment]
I also prefer `hepstats` and it can be used as it is. `import hepstats as hs` seems weird to me but it's a French bias, hs is an acronym for "hors service" = out of order. 

If everyone is happy with `hepstats` I can proceed to change the name.

**Comment by matthewfeickert** [comment]
> I also prefer `hepstats` and it can be used as it is. `import hepstats as hs` seems weird to me but it's a French bias, hs is an acronym for "hors service" = out of order.

That's a nice point and also a reminder that not every library needs to be aliased to two letters. :) :+1:

**Comment by marinang** [comment]
The package has renamed successfully to hepstats :D. Closing.
