### ISSUE TITLE
Asymptotic calculator histogram dimensionality

### ISSUE THREAD

**Issue by CrfzdPQM6** [scikit-hep/hepstats#55]
When generating the asimov histogram associated with a particular test, why is the generated histogram limited to a one-dimensional fit, implicitly by the call to `space.limit1d` [here](https://github.com/scikit-hep/hepstats/blob/cf650da0408de083e27c52b952fe4ef144014de8/src/hepstats/hypotests/calculators/asymptotic_calculator.py#L34)? This seems to exclude the possibility for hypothesis tests involving a likelihood function evaluated using a PDF with dimensionality greater than 1 which, in my naive understanding, is a desirable use-case for this calculator.

Thanks for all your work!

**Comment by jonas-eschle** [comment]
Hey, that's a good catch! Indeed, this should be working for n-dims and is not generalized.

Since zfit itself offers now also to directly create binned histograms, this could be the best way to go: https://zfit-tutorials.readthedocs.io/en/latest/tutorials/components/30%20-%20Binned%20models.html#binned-models-from-histograms

Or we could simply generalize it as it is now, the problem is maybe that it only takes the midpoint, which is probably often good enough but maybe creates a small bias.

**Comment by CrfzdPQM6** [comment]
I suppose either way this will require some development (and a new release!) before I can use it. There is no workaround, right?

**Comment by marinang** [comment]
Hey, as far as I remember the asymptotic method was only documented for 1D problems (I.e 1D parameter of interest)

You should probably check the papers and see if there is an extension to N-dim.

**Comment by CrfzdPQM6** [comment]
It's a 1D poi, but that's a different thing to requiring a 1D space for the asimov dataset. The pdf can be multidimensional while the scan is still over a 1 dimensional yield parameter, for example.
